# ─── TEL — The Experience Layer ───────────────────────────────────────────────
# Multi-stage Docker build
# Stage 1: deps      — install npm packages
# Stage 2: builder   — next build (output: standalone)
# Stage 3: runner    — minimal production image
#
# Deploy: theexperiencelayer.org / Hetzner Helsinki / Coolify
#
# Build: docker build -t tel-app .
# Run:   docker run -p 3000:3000 --env-file .env.local tel-app

# ── Stage 1: Dependencies ─────────────────────────────────────────────────────
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --frozen-lockfile

# ── Stage 2: Build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
RUN npm run build

# ── Stage 3: Runner (production, minimal) ─────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# ── Copy standalone server ───────────────────────────────────────────────────
# The standalone dir contains: server.js, node_modules/ (pruned), .next/server/
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# ── Copy static assets (CSS, JS chunks) ─────────────────────────────────────
# CRITICAL: standalone does NOT include .next/static — must be copied separately
# These are served by server.js from .next/static/ relative to its location
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# ── Copy public assets (manifest.json, icons) ───────────────────────────────
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000

# Health check — polls /api/health which checks SOUFFLE availability
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health 2>/dev/null | grep -q '"ok":true' || exit 1

# server.js is generated by next build when output: 'standalone'
CMD ["node", "server.js"]
