# ─── TEL — The Experience Layer ───────────────────────────────────────────────
# Multi-stage Docker build
# Stage 1: deps
# Stage 2: builder
# Stage 3: runner (production, minimal)
#
# Deploy to: theexperiencelayer.org
# Infrastructure: Hetzner Helsinki via Coolify
#
# Build: docker build -t tel-app .
# Run:   docker run -p 3000:3000 --env-file .env.local tel-app

# ── Stage 1: Install dependencies ─────────────────────────────────────────────
FROM node:20-alpine AS deps

# Install build tools for native modules (if any)
RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install ALL dependencies (including devDependencies for build)
RUN npm ci --frozen-lockfile

# ── Stage 2: Build application ────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build Next.js (uses output: 'standalone')
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Validate required env vars at build time (API keys are runtime-only)
RUN npm run build

# ── Stage 3: Production runner ────────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy standalone output (generated by output: 'standalone')
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Set correct permissions
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health 2>/dev/null | grep -q '"ok"' || exit 1

CMD ["node", "server.js"]
